frontend updates
musi-tech/pdea-coem pull request #28
Opened 2024-07-21 17:07 UTC by ATHARVA262005

2024-07-21 17:15 UTC, SAYUK09 requested changes
Take a look at the requested changes

2024-07-21 17:15 UTC, SAYUK09 commented on src/PageTemplate/DepartmentTemplate.jsx
> -        </div>
Don't Delete. Only Comment.

2024-07-21 17:38 UTC, SAYUK09 requested changes

2024-07-21 17:38 UTC, SAYUK09 commented on src/Components/HeroVid/HeroVid.css
>    }
double semi colon

2024-07-21 20:25 UTC, ATHARVA262005 commented on src/Components/HeroVid/HeroVid.css
>    }
herovid.css is unused , we use tailwind css now its just for backup

2024-07-21 20:25 UTC, ATHARVA262005 commented on src/PageTemplate/DepartmentTemplate.jsx
> -        </div>
that section isn't necessary now

2024-07-22 05:09 UTC, SAYUK09 commented on src/Components/HeroVid/HeroVid.css
>    }
If it's not being used, can't we delete it?
And if we want to keep it, can we please get rid of the syntax error.

2024-07-22 05:10 UTC, SAYUK09 commented on src/PageTemplate/DepartmentTemplate.jsx
> -        </div>
But won't we need it in future?
It would be easy to just uncomment and start using it, won't it?

2024-07-22 10:57 UTC, merged